#!/usr/bin/env node
/*
 * One set of models, two products.
 *
 * apps/onsite runs SQLite on a box in the restaurant; apps/cloud runs Postgres
 * for many tenants. Only the datasource provider and the client output path
 * differ, so those live here and the 255 lines of models are written once —
 * a field added to Order cannot reach one product and miss the other.
 *
 * Generated files are committed so a clone builds without running this first,
 * and CI re-runs it to prove they are in step.
 *
 * Usage: node packages/db/compose.mjs [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const models = readFileSync(path.join(here, "models.prisma"), "utf8");

const TARGETS = [
  {
    name: "onsite",
    file: path.join(here, "../../apps/onsite/prisma/schema.prisma"),
    provider: "sqlite",
    output: "../src/generated/prisma",
    note:
      "SQLite: a single file on the restaurant's own machine, so service\n" +
      "// continues when the internet does not.",
  },
  {
    name: "cloud",
    file: path.join(here, "../../apps/cloud/prisma/schema.prisma"),
    provider: "postgresql",
    output: "../src/generated/prisma",
    note:
      "Postgres: one database, every row scoped by organizationId. Its client\n" +
      "// is a superset of the SQLite one, so shared domain code compiles for both\n" +
      "// as long as it stays inside the narrower SQLite surface — no mode:\n" +
      "// \"insensitive\", no skipDuplicates.",
  },
];

const header = (t) => `// GENERATED by packages/db/compose.mjs — do not edit.
// Models live in packages/db/models.prisma; only the datasource differs.
//
// ${t.note}
//
// No enums, arrays or native types anywhere in the models: that started as a
// SQLite limitation and is now the contract that lets both providers share
// one schema. Constrained values are strings validated by Zod at the edges.

generator client {
  provider = "prisma-client"
  output   = "${t.output}"
}

datasource db {
  provider = "${t.provider}"
}

`;

const check = process.argv.includes("--check");
let drift = false;

for (const t of TARGETS) {
  const wanted = header(t) + models;
  let current = null;
  try {
    current = readFileSync(t.file, "utf8");
  } catch {
    /* not generated yet */
  }
  if (current === wanted) {
    console.log(`  ${t.name}: up to date`);
    continue;
  }
  if (check) {
    console.error(`  ${t.name}: OUT OF DATE — run node packages/db/compose.mjs`);
    drift = true;
    continue;
  }
  writeFileSync(t.file, wanted);
  console.log(`  ${t.name}: written (${t.provider})`);
}

if (drift) process.exit(1);
